spring:
  application:
    name: "online-store"

  r2dbc:
    url: r2dbc:postgresql://${DB_URL}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASS}

  liquibase:
    url: jdbc:postgresql://${DB_URL}?currentSchema=${DB_SCHEMA}
    user: ${DB_USER}
    password: ${DB_PASS}
    enabled: true

  thymeleaf:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /store

store:
  view:
    itemsInRow: 3

r2dbc:
  datasource:
    driver: "postgresql"
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_DATABASE}
    schema: ${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASS}
