spring:
  application:
    name: "online-store"

  datasource:
    url: jdbc:postgresql://${DB_URL}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  liquibase:
    default-schema: ${DB_SCHEMA}
    enabled: true

  thymeleaf:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /store

store:
  view:
    itemsInRow: 3