services:

  store_db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis_cache:
    image: redis:8.2.1-bookworm
    ports:
      - "6379:6379"
    command: redis-server

  payment-app:
    build:
      context: ../
      dockerfile: /payment-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_URL: store_db/store_db
      DB_SCHEMA: store
      DB_USER: admin
      DB_PASS: password
    depends_on:
      - store_db

  store-app:
    build:
      context: ../
      dockerfile: /store-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: store_db/store_db
      DB_HOST: store_db
      DB_PORT: 5432
      DB_DATABASE: store_db
      DB_SCHEMA: store
      DB_USER: admin
      DB_PASS: password
      PAYMENT_SERVICE_URL: "http://payment-app:8081/payment"
    depends_on:
      - store_db
      - payment-app