services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.5
    environment:
      KC_HOSTNAME_PORT: 8082
      KC_HTTP_PORT: 8082
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./realms:/opt/keycloak/data/import
    ports:
      - "8082:8082"
    command: start-dev --import-realm

  store_db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: store_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis_cache:
    image: redis:8.2.1-bookworm
    ports:
      - "6379:6379"
    command: redis-server

  payment-app:
    build:
      context: ../
      dockerfile: /payment-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_URL: store_db/store_db
      DB_SCHEMA: store
      DB_USER: admin
      DB_PASS: password
      KEYCLOAK_URL: "http://keycloak:8082/realms/master"
    depends_on:
      - store_db

  store-app:
    build:
      context: ../
      dockerfile: /store-service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: store_db/store_db
      DB_HOST: store_db
      DB_PORT: 5432
      DB_DATABASE: store_db
      DB_SCHEMA: store
      DB_USER: admin
      DB_PASS: password
      PAYMENT_SERVICE_URL: "http://payment-app:8081/payment"
      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
      KEYCLOAK_URL: "http://keycloak:8082/realms/master"
      KEYCLOAK_CLIENT_SECRET: ac3BMBFbnrsmPfIB4L7aWHvTrBnumYoj
    depends_on:
      - store_db
      - payment-app