spring:
  application:
    name: store-service

  webflux:
    base-path: /store

  r2dbc:
    url: r2dbc:postgresql://${DB_URL}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASS}

  liquibase:
    url: jdbc:postgresql://${DB_URL}?currentSchema=${DB_SCHEMA}
    user: ${DB_USER}
    password: ${DB_PASS}
    enabled: true

  thymeleaf:
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 8080

store:
  view:
    itemsInRow: 3
  cache:
    itemCachePrefix: "item:"
    orderCachePrefix: "order:"
    allOrdersCachePrefix: "all_orders:"
    ttl: PT120S

r2dbc:
  datasource:
    driver: "postgresql"
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_DATABASE}
    schema: ${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASS}

payment:
  service:
    url: ${PAYMENT_SERVICE_URL}
