openapi: 3.0.4
info:
  title: Payment System v1.0
  description: |-
    This is OpenAPI 3.0 specification for online store payment system.  

    Some useful links:
    - [The Online Store repository](https://github.com/AlTriV/online-store)
  contact:
    email: aliaksei.trynda@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:8081/payment
paths:
  /balance:
    get:
      summary: Get current balance
      description: Request balance
      operationId: getBalance
      parameters:
        - name: username
          in: query
          description: Username
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'
  /pay:
    post:
      summary: Purchase order
      description: Request to purchase order
      operationId: purchase
      requestBody:
        description: Purchase order
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseRequest'
        required: true
      responses:
        '200':
          description: Purchase complete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseResponse'
        '400':
          description: Invalid input
components:
  schemas:
    BalanceResponse:
      type: object
      description: Get balance request
      required:
        - balance
        - username
      properties:
        balance:
          type: integer
          format: int64
          description: Balance value
          example: 100000
        username:
          type: string
          maxLength: 50
          description: Username
    PurchaseRequest:
      required:
        - requestId
        - price
        - username
      type: object
      description: Request to purchase order
      properties:
        requestId:
          type: string
          format: uuid
          description: Purchase order request uuid
        price:
          type: integer
          format: int64
          description: Order total price
          example: 1200
        username:
          type: string
          maxLength: 50
          description: Username
    PurchaseResponse:
      required:
        - requestId
        - purchaseResult
        - username
      type: object
      description: Purchase response
      properties:
        requestId:
          type: string
          format: uuid
          description: Purchase order request uuid
        username:
          type: string
          maxLength: 50
          description: Username
        purchaseResult:
          type: boolean
          description: Is purchase success
          example: false
        errorMessage:
          type: string
          description: Error message if purchase is unsuccess
          example: "Have no enough cash"